#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check
  methods: [POST]

api_graphql_entrypoint:
  path: /api/graphql
  controller: api_platform.graphql.action.entrypoint
